### ISSUE TITLE
Auto update lambda 

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/stats-collector#6]
Capturing our conversation for further actions @arunasank

Like discussed at present whenever I make changes to the script I manually update the lambda. Instead as and when a change is published to the `master` branch in GitHub, changes should be reflected in AWS.

@smit1678

**Comment by ramyaragupathy** [comment]
Working on this today cc @arunasank

**Comment by ramyaragupathy** [comment]
### Changes done so far:

Include `cloudfriend` [helper functions](https://github.com/mapbox/cloudfriend/blob/master/lib/shortcuts/readme.md) - to list a scheduled lambda as a resource. Also this resources assumes code base to be present in a S3 bucket as a `code.zip` file. While deploying this stack, I encounter `Access denied` issue.

Per chat w/ @arunasank - there are two possibilities for us here:

1. Setup a stack with a helper shell script that pulls the latest commit from stats-collector master branch and run the index.js file. In this case instead of a lambda we will have the script executed on an EC2. Also the latest git commit needs to be updated manually everytime a new code is pushed
2. Go with the current approach. That is setup a stack with a lambda related resources which pulls the code from a S3 bucket.

We are going forward with the second approach as it is efficient from a cost perspective.

**Tasks to be done:**
- [ ] Integrate [mapbox/stork](https://github.com/mapbox/stork) to the stats-collector repo: stork library monitors a gh repo and sync the changes to a S3 bucket. However the main stork repo is deprecated. So @arunasank will look at forking the repo for larger needs within HOT. cc @smit1678 
- [ ] Each time the code is pushed to S3 bucket, use the GitSha name instead o . just `code.zip`. This is useful in the longer run for version tracking
- [ ] Fix access denied issue and other parameter collection for the stack setup - @ramyaragupathy 


cc @smit1678

**Comment by ramyaragupathy** [comment]
Progress till Wednesday:
- [x] Stork integration to the repo & org level
- [x] cfn template creation
- [x] stack deployment
- [ ] successful lambda execution
- [ ] circle ci setup to auto update latest gitsha
